# Generated by Django 5.2.6 on 2025-09-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría'),
        ),
    ]
